import { ShieldCheck, Lock, Eye, FileText } from 'lucide-react'

export function TermsOfService() {
  return (
    <div className="animate-in fade-in slide-in-from-bottom-4 duration-500 max-w-4xl mx-auto py-10 px-4">
      <div className="flex items-center gap-4 mb-8">
        <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10 text-primary">
          <ShieldCheck className="h-6 w-6" />
        </div>
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-foreground">Terms of Service</h1>
          <p className="text-muted-foreground">Usage Guidelines for SN</p>
        </div>
      </div>

      <div className="prose prose-slate dark:prose-invert max-w-none space-y-8">
        <section className="bg-card/50 border border-border p-6 rounded-2xl shadow-sm">
          <h2 className="text-xl font-semibold mb-4 text-foreground flex items-center gap-2">
            <FileText className="h-5 w-5 text-primary" />
            1. Acceptance of Terms
          </h2>
          <p className="text-muted-foreground">Usage Guidelines for SN</p>
        </section>

        <div className="prose prose-sm md:prose-base dark:prose-invert max-w-none space-y-6 text-muted-foreground/80">
          <p>
            Welcome to SN. By accessing and using our stock prediction tools and educational content, you agree to comply with and be bound by the following terms and conditions.
          </p>

          <section className="space-y-3 text-foreground">
            <h3 className="text-xl font-bold tracking-tight">1. Educational Purpose Only</h3>
            <p className="text-muted-foreground/80 leading-relaxed">
              The predictions and analysis provided by our platform are generated by artificial intelligence models and are strictly for educational and research purposes. They do not constitute financial advice, investment recommendations, or an offer to buy or sell securities.
            </p>
          </section>

          <section className="space-y-3 text-foreground">
            <h3 className="text-xl font-bold tracking-tight">2. No Guarantee of Accuracy</h3>
            <p className="text-muted-foreground/80 leading-relaxed">
              Stock markets are inherently volatile and unpredictable. While we use advanced AI models, we do not guarantee the accuracy, completeness, or reliability of any predictions. Past performance of the model does not indicate future results.
            </p>
          </section>

          <section className="space-y-3 text-foreground">
            <h3 className="text-xl font-bold tracking-tight">3. User Responsibility</h3>
            <p className="text-muted-foreground/80 leading-relaxed">
              You acknowledge that any investment decisions you make based on information from this platform are made solely at your own risk. You should always conduct your own research or consult with a qualified financial advisor before making investment decisions.
            </p>
          </section>

          <section className="space-y-3 text-foreground">
            <h3 className="text-xl font-bold tracking-tight">4. Limitation of Liability</h3>
            <p className="text-muted-foreground/80 leading-relaxed">
              SN shall not be liable for any financial losses, damages, or missed opportunities resulting from the use of or reliance on our predictions, charts, or any other content provided on this platform.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-6 border-t border-border/50 text-sm text-muted-foreground/60 text-center">
          Last updated: September 21, 2026
        </div>
      </div>
    </div>
  )
}
